### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by youtah** [casebeer/audiogen#8]
Running Python **3.6.9**

The following script:
```
#!/usr/bin/env python3
import audiogen
audiogen.sampler.play(audiogen.tone(440))
```

Generates the error:

```
jeff@machine:~$ ./test_audio.py 
Traceback (most recent call last):
  File "./test_audio.py", line 3, in <module>
    import audiogen
  File "/home/jeff/.local/lib/python3.6/site-packages/audiogen/__init__.py", line 2, in <module>
    from .sampler import frame_rate
  File "/home/jeff/.local/lib/python3.6/site-packages/audiogen/sampler.py", line 64
    except IOError, e:
                  ^
SyntaxError: invalid syntax
```

https://github.com/casebeer/audiogen/blob/184dee2ca32c2bb4315a0f18e62288728fcd7881/audiogen/sampler.py#L64

**Comment by lysol** [comment]
This is an old, seemingly unmaintained project that hasn't been rewritten for Python 3 support.

**Comment by superpaddy98** [comment]
The error is within the library. Just "import audiogen" produces that error.
